(defun esh-tf--rule-no-command (command &optional corrections)
  (let* ((parts (plist-get command :parts))
         (old-command (car parts))
         (output (plist-get command :output)))
    (if corrections
        (let* ((prev-history-execs
                (cl-remove-if-not
                 #'esh-tf--which
                 (mapcar
                  (lambda (str)
                    (car (split-string str " ")))
                  (cl-remove-if
                   (lambda (str)
                     (string-prefix-p "fuck" (string-trim-left str)))
                   (cddr (ring-elements eshell-history-ring))))))
               (all (esh-tf--get-closest-matches
                     old-command
                     (append
                      prev-history-execs
                      (esh-tf--get-all-executables)))))
          (mapcar
           (lambda (str)
             (concat str (when (cdr parts)
                           (concat " "
                                   (string-join (cdr parts) " ")))))
           (delete-dups all)))
      (and (not (esh-tf--which old-command))
           (string-match-p "not found" output)
           (FM-map-close-matches
            old-command
            (esh-tf--get-all-executables))))))

(defvar esh-tf-rules '((ag-literal . 0)
                       (aws-cli . 0)
                       (cargo . 0)
                       (cargo-no-command . 0)
                       (cd-correction . 0)
                       (cd-mkdir . 0)
                       (cd-parent . 0)
                       (chmod-x . 0)
                       (composer-not-command . 0)
                       (cp-omitting-directory . 0)
                       (cpp11 . 0)
                       (dirty-untar . 0)
                       (dirty-unzip . 0)
                       (django-south-ghost . 0)
                       (django-south-merge . 0)
                       (docker-not-command . 0)
                       (dry . 900)
                       (fab-command-not-found . 0)
                       (fix-alt-space . 0)
                       (fix-file . 0)
                       (gem-unknown-command . 0)
                       (git-add . 0)
                       (git-add-force . 0)
                       (git-bisect-usage . 0)
                       (git-branch-delete . 0)
                       (git-branch-exists . 0)
                       (git-branch-list . 0)
                       (git-checkout . 0)
                       (git-diff-no-index . 0)
                       (git-diff-staged . 0)
                       (git-fix-stash . 0)
                       (git-flag-after-filename . 0)
                       (git-help-aliased . 0)
                       (git-not-command . 0)
                       (git-pull . 0)
                       (git-pull-clone . 0)
                       (git-pull-uncommitted-changes . 0)
                       (git-push . 0)
                       (git-push-different-branch-names . 0)
                       (git-push-pull . 0)
                       (git-push-without-commits . 0)
                       (git-rebase-no-changes . 0)
                       (git-remote-delete . 0)
                       (git-rm-local-modifications . 0)
                       (git-rm-recursive . 0)
                       (git-rm-staged . 0)
                       (git-rebase-merge-dir . 0)
                       (git-remote-seturl-add . 0)
                       (git-stash . 0)
                       (git-stash-pop . 900)
                       (git-tag-force . 0)
                       (git-two-dashes . 0)
                       (go-run . 0)
                       (gradle-no-task . 0)
                       (gradle-wrapper . 0)
                       (grep-arguments-order . 0)
                       (grep-recursive . 0)
                       (grunt-task-not-found . 0)
                       (gulp-not-task . 0)
                       (has-exists-script . 0)
                       (heroku-not-command . 0)
                       (history . 9999)
                       (hostscli . 0)
                       (ifconfig-device-not-found . 0)
                       (java . 0)
                       (javac . 0)
                       (lein-not-task . 0)
                       (ln-no-hard-link . 0)
                       (ln-s-order . 0)
                       (ls-all . 0)
                       (ls-lah . 0)
                       (man . 0)
                       (man-no-space . 2000)
                       (mercurial . 0)
                       (missing-space-before-subcommand . 4000)
                       (mkdir-p . 0)
                       (mvn-no-command . 0)
                       (mvn-unknown-lifecycle-phase . 0)
                       (npm-missing-script . 0)
                       (npm-run-script . 0)
                       (npm-wrong-command . 0)
                       (no-command . 3000)
                       (no-such-file . 0)
                       (open . 0)
                       (pip-unknown-command . 0)
                       (php-s . 0)
                       (port-already-in-use . 0)
                       (prove-recursively . 0)
                       (python-command . 0)
                       (python-execute . 0)
                       (quotation-marks . 0)
                       (path-from-history . 800)
                       (react-native-command-unrecognized . 0)
                       (remove-trailing-cedilla . 0)
                       (rm-dir . 0)
                       (scm-correction . 0)
                       (sed-unterminated-s . 0)
                       (sl-ls . 0)
                       (ssh-known-hosts . 0)
                       (sudo . 0)
                       (sudo-command-from-user-path . 0)
                       (switch-lang . 0)
                       (systemctl . 0)
                       (touch . 0)
                       (tsuru-login . 0)
                       (tsuru-not-command . 0)
                       (tmux . 0)
                       (unknown-command . 0)
                       (vagrant-up . 0)
                       (whois . 0)
                       (workon-doesnt-exists . 0)
                       (yarn-alias . 0)
                       (yarn-command-not-found . 0)
                       (yarn-command-replaced . 0)
                       (yarn-help . 0)))
